---
title: "Multiracial Intermarriage"
author: "Aaron Gullickson, Sociology, University of Oregon"
abstract: "abstract here"
keywords: keyword 1; keyword 2
description: a description
thanks: Thanks to everyone.
execute: 
  eval: true
  echo: false
  warning: false
  error: false
format: 
  pdf:
    fig-pos: t
    fig-height: 4
    keep-md: false
    keep-tex: false
    documentclass: scrartcl # LaTeX document class
    #fontfamily: accanthis   # font family, see below for options
    fontsize: 12pt          # font size (typically 10pt, 11pt, or 12pt)
    linestretch: 1          # line spacing (1 for single, 2 for double)
    geometry: margin=0.5in  # controls the margin size
    papersize: letter       # controls the paper type
    include-in-header: 
      text: |
        \usepackage{booktabs}
        \usepackage{dcolumn}
bibliography: ../project.bib
csl: resources/asa.csl
editor: source
---

```{r setup}
#| include: false
# load libraries
library(here)
source(here("analysis","check_packages.R"))
# load functions
source(here("analysis","useful_functions.R"))
# load data

```

# Introduction

-   One of the greatest potential catalysts for change in US racial dynamics over the last half century has been the creation of individuals whose parents cross racial lines. Although multiraciality is not a new phenomenon, a "biracial baby boom" from the late 20th century and early 21st century has led to changes in official race reporting in the US and greater questioning of racial categories at large.
-   However, this biracial baby boom may mislead regarding the long term impact of multiraciality on the US's racial future. Just like the real baby boom, the biracial baby boom is an anomaly driven by rapid historic change in the US. And like the real baby boom, the biracial baby boom distorts the demographic reality from what stable population dynamics would expect. In this case, the biracial baby boom moved the "generational loci" of multiraciality to the immediately preceding generation and thus increased the salience and meaning of what that multiracial identity means for individuals who recognized a multiracial family heritage.
-   The biracial baby boom however creates the conditions for its own demise, however. As the children of that boom continue to grow into adulthood, they form their own families and produce a new generation of children where the generational loci of multiraciality will be more distant and who thus may think about their multiracial ancestry differently. In other words, we will move into a future that looks something more like the past in which variation in generational loci will combine with other social factors to create a tangled and complex web of racial identification and classification, rather than much brighter lines identified by those whose parents belonged to different races. <!-- TODO: CITE BRATTER'S WORK HERE SOMEWHERE -->
-   In attempting to untangle this complexity, one of the key issues will be who biracial individuals partner with and have children with. We know that who one partners with is heavily influenced by race, but how will this play out for those with strong racial attachments across traditional racial lines? In this article, I take up that question by examining the patterns of interracial marriage for self-identified multiracial individuals in ACS and Census data.
-   Tease of the results.

# Background

* Do I start with the history or with the concept of generational locus? Maybe locus as this is kind of the central concept behind all of this.

* The long history of multiraciality
  * The creation of multiracial individuals is not a new thing. 
  * Deep irony of racialized systems is that the creation and institution of racially defined boundaries creates its own paradox - individuals who do not fit neatly within those boundaries. All racialized systems develop systems for resolving the ambiguity of such individuals. 
  
* In the US, well-established patterns for addressing mixing among the original "racial triangle" of European settlers, African slaves, and Indigenous populations.     * Two rules of hypodescent and hyperdescent are thought to govern the relationship between white and black miscegenation and white and Indigenous miscegenation specifically.
    * An alternative explanation focuses on the dominant/recessive characteristics of ancestry/blood. In this schema, black blood is the strongest as it dominates other ancestries and is thus can never be assimilated. Indigenous ancestry is the most recessive as it fades in combination with *both* white and black ancestry. Whiteness is somewhere in the middle. 
    * Either way, the consequence of this is that the one-drop rule made mixing between black and white individuals invisible in the genealogies of their ancestors. While such ancestry might have been known, it was rarely discussed. In the case of black descendants, it would often reflect a history of racial sexual violence. In the case of white descendants, the threat of "invisible blackness" made it necessary to excise such history from the family tree.
    * In contrast, Indigenous ancestry was not disqualifying from anything. To be a white or a black person with some indigenous ancestry was not particularly remarkable (cite )

This differs from place to place, but in the US it often coincided with a denial coupled with different logics of assimilation for black and indigenous ancestry. GO INTO DETAILS
  * This leads to complex family histories, some of them invisible, some of them noted, but with an intense social pr
* Review of the biracial baby boom
  * When did it start? 1960s
  * Why did it start? removal of anti-miscegenation laws, partial integration, growing diversity, a greater willingness to recognize the multiracial ancestry of these children. 
  * consequences: multiracial movement and the check all that apply option; greater potential fluidity in racial identification, potential challenge to the one-drop rule
  
* Note that one of Bratter's findings is that multiracial identification declines when the parents share a common racial ancestry (so white/asian & white often just becomes white).
  
* What are the possibilities for outcomes and what do they mean?
  * Is there a tendency to partner with individuals of exactly the same multiracial ancestry? (multiracial endogamy)
  * Is there a tendency to marry other multiracial individuals regardless of combination? (shared collective experience of multiraciality)
  * How strong is the tendency to partner with someone from the same constituent group? (partial racial endogamy)
    * Does this vary by the kind of constituent group? Test two hypotheses:
      * tendency to prefer whiteness
      * tendency to avoid blackness
  * When individuals marry fellow multiracials do we see a similar tendency to prefer whiteness and avoid blackness among the constituent possibilities?

# Data and Methods

# Results

# Conclusions
