---
title: "Research Analysis Notebook"
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
load(here("data","data_constructed","models.RData"))
load(here("data","data_constructed","markets.RData"))
```



```{r}
#| label: create-coef-table
get_coefs <- function(x) {
  temp <- coef(x)[,c(1,2)]
  return(tibble(variable=rownames(temp), coef=temp[,1], se=temp[,2]))
}

coef_short_sym <- get_coefs(model_short_sym) |>
  filter(str_detect(variable, "race_exog")) |>
  mutate(variable=str_replace(variable, "race_exog",""))

coef_short_asym <- get_coefs(model_short_asym) |>
  filter(str_detect(variable, "race_exog_asym")) |>
  mutate(variable=str_replace(variable, "race_exog_asym",""))


coef_full <- get_coefs(model_full_sym) |>
  filter(str_detect(variable, "race_exog_full")) |>
  mutate(variable=str_replace(variable, "race_exog_full",""))
```


```{r}
#| label: fig-odds-ratios-single
#| fig-cap: Odds of interracial marriage with single race groups for each multiracial group. The purple dots indicate cases where the single race group is constituent of the multiracial group, while the green dots indicate cases where the single race group is not constituent of the multiracial group. 83.4% and 95% confidence intervals are shown for each estimate with thick and thin bars, respectively. The red dashed line indicates the corresponding odds of intermarriage for single race groups constituent of the multiracial group (e.g. White and Black couples for the White/Black multiracial group). The dashed grey lines indicates the case of an odds equal to one, meaning this type of intermarriage is as likely as endogamy.
single_race <- coef_short_sym |> 
  filter(!str_detect(variable, "/|Latino")) |>
  mutate(multiple_race=str_replace(variable, "\\.", "/"),
         multiple_race=factor(multiple_race,
                              levels=c("White/Asian","Black/Indigenous",
                                       "White/Indigenous","Indigenous/Asian",
                                       "White/Black","Black/Asian")))

# the somewhat odd regular expression \\..*/ will identify all the names with a 
# period followed by some characters followed by a forward slash. This will give
# me all cases of a single race/multiple race marriage
coef_short_sym |>
  filter(str_detect(variable, "\\..*/")) |>
  mutate(single_race=str_split(variable, "\\.", simplify=TRUE)[,1],
         multiple_race=str_split(variable, "\\.", simplify=TRUE)[,2],
         constituent=str_detect(multiple_race, single_race),
         single_race=factor(single_race, 
                            levels=c("Latino","Asian","Indigenous","Black",
                                     "White")),
         multiple_race=factor(multiple_race,
                              levels=c("White/Asian","Black/Asian",
                                       "White/Indigenous","Black/Indigenous",
                                       "White/Black","Indigenous/Asian"))) |>
  ggplot(aes(x=single_race, y=exp(coef), color=constituent))+
  geom_linerange(linewidth=1.25, 
                  aes(ymax=exp(coef+1.386*se), ymin=exp(coef-1.386*se)))+
  geom_linerange(linewidth=0.5, 
                  aes(ymax=exp(coef+1.96*se), ymin=exp(coef-1.96*se)))+
  geom_point(size=2)+
  geom_hline(data=single_race, aes(yintercept=exp(coef)), linetype=2, 
             color="red")+
  geom_hline(yintercept=1, linetype=5, linewidth=0.5, color="grey30")+
  #geom_hline(yintercept=exp(filter(coef, variable=="Multi/Multi")$coef), 
  #           linetype=2, color="blue")+
  coord_flip()+
  facet_wrap(~multiple_race, ncol=2)+
  #scale_y_continuous(limits=c(0,1.2))+
  scale_color_viridis_d(direction=-1, end=0.75)+
  labs(x="single race partner", y="odds of marriage with single race partner relative to multiracial endogamy")+
  theme_bw()+
  theme(legend.position = "none")
```

```{r}
#| label: fig-odds-ratios-multi
#| fig-cap: Odds of interracial marriage with other multiracial groups for each multiracial group. The purple dots indicate cases where the ego multiracial group has overlapping partial ancestry with the other multiracial group, while the green dots indicate cases where is no overlap. 83.4% and 95% confidence intervals are shown for each estimate with thick and thin bars, respectively. The dashed grey lines indicates the case of an odds equal to one, meaning this type of intermarriage is as likely as endogamy (e.g. White/Black person marrying White/Black person).
single_race <- coef_full |> 
  filter(!str_detect(variable, "/|Latino")) |>
  mutate(multiple_race=str_replace(variable, "\\.", "/"),
         multiple_race=factor(multiple_race,
                              levels=c("White/Asian","Black/Indigenous",
                                       "White/Indigenous","Indigenous/Asian",
                                       "White/Black","Black/Asian")))

# the somewhat odd regular expression \\..*/ will identify all the names with a 
# period followed by some characters followed by a forward slash. This will give
# me all cases of a single race/multiple race marriage
temp <- coef_full |>
  filter(str_detect(variable, "/.*\\.*/")) |>
  mutate(race_ego=str_split(variable, "\\.", simplify=TRUE)[,1],
         race_choice=str_split(variable, "\\.", simplify=TRUE)[,2],
         race_cons1=str_split(race_ego, "/", simplify=TRUE)[,1],
         race_cons2=str_split(race_ego, "/", simplify=TRUE)[,2],
         overlap=str_detect(race_choice, race_cons1) | 
           str_detect(race_choice, race_cons2)) |>
  select(race_ego, race_choice, overlap, coef, se)
         
# this needs to be duplicated so that each possibility is both ego and choice.
# easiest way to do this is to create a second one, flip the variables and 
# bind them together
temp2 <- temp
temp <- temp2 |>
  mutate(race_ego=temp$race_choice,
         race_choice=temp$race_ego) |>
  bind_rows(temp) |>
  mutate(race_ego=factor(race_ego, 
                         levels=c("White/Asian","Black/Asian",
                                  "White/Indigenous","Black/Indigenous",
                                  "White/Black","Indigenous/Asian")),
         race_choice=factor(race_choice, 
                         levels=c("White/Asian","Black/Asian",
                                  "White/Indigenous","Black/Indigenous",
                                  "White/Black","Indigenous/Asian")))


ggplot(temp, aes(x=race_choice, y=exp(coef), color=overlap))+
  geom_linerange(linewidth=1.25, 
                 aes(ymax=exp(coef+1.386*se), ymin=exp(coef-1.386*se)))+
  geom_linerange(linewidth=0.5, 
                 aes(ymax=exp(coef+1.96*se), ymin=exp(coef-1.96*se)))+
  geom_point(size=2)+
  #geom_hline(data=single_race, aes(yintercept=exp(coef)), linetype=2, 
  #           color="red")+
  geom_hline(yintercept=1, linetype=5, linewidth=0.5, color="grey30")+
  #geom_hline(yintercept=exp(filter(coef, variable=="Multi/Multi")$coef), 
  #           linetype=2, color="blue")+
  coord_flip()+
  facet_wrap(~race_ego, ncol=2)+
  scale_y_log10()+
  scale_color_viridis_d(direction=-1, end=0.75)+
  labs(x="multiple race partner", 
       y="odds of marriage with multiple race partner relative to multiracial endogamy")+
  theme_bw()+
  theme(legend.position = "none")
```

```{r}
#| label: fig-gender-asymmetric
#| fig-cap: Odds of interracial marriage with single race groups for each multiracial group, separately by the gender combination of the partners. 83.4% and 95% confidence intervals are shown for each estimate with thick and thin bars, respectively. The dashed grey lines indicates the case of an odds equal to one, meaning this type of intermarriage is as likely as endogamy. Indigenous+Black/Indigenous and Indigenous+Black/Asian pairings have been removed due to very large confidence intervals.

# before period is husband, after period is wife
temp <- coef_short_asym |>
  filter(str_detect(variable, "/") & !str_detect(variable, "Multi")) |>
  mutate(race_husband=str_split(variable, "\\.", simplify=TRUE)[,1],
         race_wife=str_split(variable, "\\.", simplify=TRUE)[,2],
         race_label=ifelse(str_detect(race_husband, "/"), 
                           paste(race_wife, " Female", 
                                 sep=""),
                           paste(race_husband, " Male", 
                                 sep="")),
         multiple_race=ifelse(str_detect(race_husband, "/"), race_husband,
                            race_wife),
         single_race=ifelse(str_detect(race_husband, "/"), race_wife,
                            race_husband),
         race_group=paste(single_race, ".", multiple_race, sep=""),
         single_race=factor(single_race, 
                            levels=c("Latino","Asian","Indigenous","Black",
                                     "White")),
         multiple_race=factor(multiple_race,
                              levels=c("White/Asian","Black/Asian",
                                       "White/Indigenous","Black/Indigenous",
                                       "White/Black","Indigenous/Asian")),
         ) |>
  arrange(multiple_race, single_race, race_label)

temp |>
  filter(race_group!="Indigenous.Black/Indigenous" &  # CIs too big
           race_group!="Indigenous.Black/Asian") |>
  ggplot(aes(x=fct_inorder(race_label), y=exp(coef), color=single_race))+
  geom_hline(yintercept=1, linetype=5, linewidth=0.5, color="grey30")+
  geom_linerange(linewidth=1.25, 
                 aes(ymax=exp(coef+1.386*se), ymin=exp(coef-1.386*se)))+
  geom_linerange(linewidth=0.5, 
                 aes(ymax=exp(coef+1.96*se), ymin=exp(coef-1.96*se)))+
  geom_point(size=2)+
  coord_flip()+
  facet_wrap(~multiple_race, ncol=2)+
  scale_color_viridis_d(direction=-1, end=1)+
  theme_bw()+
  labs(color="Single race partner",
       x="single race partner", 
       y="odds of marriage with single race partner relative to multiracial endogamy")
```

```{r}
#| label: create-partner-df
couples <- mar_markets[[1]] |> filter(choice)
temp <- couples |>
  filter(raceh=="White/Black" | racew=="White/Black") |>
  mutate(race_spouse=ifelse(raceh=="White/Black", 
                            as.character(racew), as.character(raceh)))
husbands <- couples |>
  #filter(str_detect(raceh, "/")) |>
  mutate(race_ego=raceh, 
         race_spouse=racew,
         gender="husband") |>
  select(race_ego, race_spouse, gender)
wives <- couples |>
  #filter(str_detect(racew, "/")) |>
  mutate(race_ego=racew, 
         race_spouse=raceh,
         gender="wife") |>
  select(race_ego, race_spouse, gender)
partner_choice <- bind_rows(husbands, wives) |>
  mutate(race_spouse=factor(race_spouse, 
                            levels=c("White","Black","Indigenous","Asian","Latino","White/Black",
                                     "White/Indigenous","White/Asian","Black/Indigenous","Black/Asian",
                                     "Indigenous/Asian")))
```

```{r}
#| label: fig-partner-panel
#| fig-cap: Distribution of partner's race for multiracial respondents, separately by panel
partner_choice |>
  filter(str_detect(race_ego, "/")) |>
  ggplot(aes(x=fct_rev(race_spouse), y=after_stat(prop), group=1))+
  geom_bar(position="dodge")+
  facet_wrap(~race_ego)+
  scale_y_continuous(labels=scales::percent)+
  labs(x=NULL, y=NULL)+
  coord_flip()+
  theme_bw()
```

```{r}
#| label: fig-partner-color
#| fig-cap: Distribution of partner's race for multiracial respondents
partner_choice |>
  filter(str_detect(race_ego, "/")) |>
  mutate(race_ego=factor(race_ego, 
                         levels=c("White/Asian","White/Indigenous","White/Black",
                                  "Indigenous/Asian","Black/Asian","Black/Indigenous"))) |>
  ggplot(aes(x=fct_rev(race_spouse), y=..prop.., group=race_ego, fill=race_ego))+
  geom_bar(position="dodge")+
  scale_y_continuous(labels=scales::percent)+
  scale_fill_manual(values = pnw_palette("Bay", 6))+
  labs(x=NULL, y=NULL)+
  coord_flip()+
  theme_bw()
```


```{r}
#| label: fig-partner-full
#| fig-cap: Distribution of partner's race for all respondents, separately by gender and race of ego respondent
ggplot(partner_choice,
       aes(x=fct_rev(race_spouse), y=..prop.., group=gender, fill=gender))+
  geom_bar(position="dodge")+
  facet_wrap(~race_ego)+
  scale_y_continuous(labels=scales::percent)+
  labs(x=NULL, y=NULL)+
  coord_flip()+
  theme_bw()
```