---
title: "Model Running Notebook"
---

```{r}
#| label: timestamp-start
timestamp()
```

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
load(here("data","data_constructed","markets.RData"))
```

# Introduction

I move the running of the models to a dedicated script because they can take a long time to run.

## Create variables

I need to actually create the variables that the models will use. Because these will be applied to a list of market data, I am going to do this variable creation in a function.

```{r}
#| label: coding-functions
add_vars <- function(market) {
  
  #age difference 
  market$agediff <- market$ageh-market$agew
  
  #birthplace endogamy, preferred specification is:
  # 1.25: Birthplace
  # 1.5:  Both
  # 1.75: Both
  # first the strict birthplace endogamy
  birth_endog <- market$bplh==market$bplw
  # now create switches to the USA for 1.5 and 1.75 generation group
  bplh_flex <- ifelse(market$immig_genh=="1.75" | market$immig_genh=="1.75", 
                      1, market$bplh)
  bplw_flex <- ifelse(market$immig_genw=="1.75" | market$immig_genw=="1.75", 
                      1, market$bplw)
  
  market$birth_endog <- birth_endog | (bplh_flex==bplw_flex)
  
  #language endogamy 
  # The -1 cases are NEC languages, so we assume non-endogamous
  market$language_endog <- ifelse(market$langh<0 | market$langw<0, 
                                  FALSE, market$langh==market$langw)
  
  ## Education terms ##
  
  #educational hypergamy/hypogamy
  market$hypergamy <- market$educh > market$educw
  market$hypogamy <- market$educh < market$educw
  
  #educational crossing
  market$edcross_hs <- (market$educh>="HS" & market$educw<"HS") | 
    (market$educw>="HS" & market$educh<"HS")
  market$edcross_sc <- (market$educh>="SC" & market$educw<"SC") | 
    (market$educw>="SC" & market$educh<"SC")
  market$edcross_c <- (market$educh>="C" & market$educw<"C") | 
    (market$educw>="C" & market$educh<"C")
  
  ## Racial Exogamy Terms ##
  
  # full racial exogamy blocks
  market$race_exog_full <- createExogamyTerms(market$raceh, 
                                              market$racew, 
                                              symmetric=TRUE)
  
  # now collapse multiracial/multiracial cases to a single dummy
  market$race_exog <- ifelse(str_count(market$race_exog_full, "/")==2,
                             "Multi/Multi", 
                             as.character(market$race_exog_full))
  market$race_exog <- relevel(factor(market$race_exog), 
                              "Endog")
  
  # partial shared ancestry coding
  groups <- str_split(market$race_exog_full, "\\.")
  constituent1 <- sapply(groups, function(x) {return(x[1])})
  constituent2 <- sapply(groups, function(x) {return(x[2])})
  temp <- str_split(constituent1, "/")
  constituent1.1 <- sapply(temp, function(x) {return(x[1])})
  constituent1.2 <- sapply(temp, function(x) {return(x[2])})
  market$multi_shared_ancestry <- ifelse(market$race_exog!="Multi/Multi", FALSE,
                                         str_detect(constituent2, constituent1.1) | 
                                           str_detect(constituent2, constituent1.2))
  
  return(market)
}
```

```{r}
#| label: add-vars
mar_markets <- lapply(mar_markets, add_vars)
```

TODO: Check yourself on coding

# Run the models

```{r}
#| label: run-model
formula_base <- formula(choice~race_exog+
                          multi_shared_ancestry+
                          agediff+I(agediff^2)+
                          hypergamy+hypogamy+edcross_hs+edcross_sc+edcross_c+
                          +birth_endog+language_endog+
                          strata(group))
model <- poolChoiceModel(formula_base, data=mar_markets, method="efron")
```


```{r}
#| label: save-output
save(model, file=here("data","data_constructed","models.RData"))
```

```{r}
#| label: timestamp-end
timestamp()
```