---
title: "Supplementary Materials for Blurring the Marriage Market: Contemporary Patterns of Multiracial Marriage"
format:
  pdf:
    geometry: margin=0.5in
    keep-tex: false
    fig-pos: "!t"
    include-in-header: 
      text: |
        \usepackage{dcolumn}
        \usepackage{longtable}
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
load(here("data","data_constructed","models.RData"))
```

```{r}
#| label: full-models
#| results: asis

coef_names <- c("Husband age - wife age", 
                "Husband age - wife age sq.",
                "Educational female hypergamy", 
                "Educational femaly hypogamy",
                "Educational crossing, high school", 
                "Educational crossing, some college",
                "Educational crossing, college",
                "Birthplace endogamy", 
                "Language endogamy",
                "Race alternate, White-Indigenous", 
                "Race alternate, White-Asian",
                "Race alternate, Black-Indigenous",
                "Race alterante, Black-Asian",
                "Race alternate, Asian-Indigenous",
                "Exogamy, White-Black/White-Indigenous",
                "Exogamy, White-Black/White-Asian",
                "Exogamy, White-Black/Black-Indigenous",
                "Exogamy, White-Black/Black-Asian",
                "Exogamy, White-Black/Asian-Indigenous",
                "Exogamy, White-Indigenous/White-Asian",
                "Exogamy, White-Indigenous/Black-Indigenous",
                "Exogamy, White-Indigenous/Black-Asian",
                "Exogamy, White-Indigenous/Asian-Indigenous",
                "Exogamy, White-Asian/Black-Indigenous",
                "Exogamy, White-Asian/Black-Asian",
                "Exogamy, White-Asian/Asian-Indigenous",
                "Exogamy, Black-Indigenous/Black-Asian",
                "Exogamy, Black-Indigenous/Asian-Indigenous",
                "Exogamy, Black-Asian/Asian-Indigenous",
                "Exogamy, multiracial/multiracial, no shared ancestry",
                "Exogamy, multiracial/multiracial, shared ancestry",
                "Race alternate, Black",
                "Race alternate, Indigenous",
                "Race alternate, Asian",
                "Race alternate, Latino",
                "Race alternate, White-Black",
                "Exogamy, Asian/Asian-Indigenous",
                "Exogamy, Asian/Black-Asian",
                "Exogamy, Asian/Black-Indigenous",
                "Exogamy, Asian/Latino",
                "Exogamy, Asian/White-Asian",
                "Exogamy, Asian/White-Black",
                "Exogamy, Asian/White-Indigenous",
                "Exogamy, Black/Asian",
                "Exogamy, Black/Asian-Indigenous",
                "Exogamy, Black/Black-Asian",
                "Exogamy, Black/Black-Indigenous",
                "Exogamy, Black/Indigenous",
                "Exogamy, Black/Latino",
                "Exogamy, Black/White-Asian",
                "Exogamy, Black/White-Black",
                "Exogamy, Black/White-Indigenous",
                "Exogamy, Indigenous/Asian",
                "Exogamy, Indigenous/Asian-Indigenous",
                "Exogamy, Indigenous/Black-Asian",
                "Exogamy, Indigenous/Black-Indigenous",
                "Exgoamy, Indigenous/Latino",
                "Exogamy, Indigenous/White-Asian",
                "Exgoamy, Indigenous/White-Black",
                "Exogamy, Indigenous/White-Indigenous",
                "Exogamy, Latino/Asian-Indigenous",
                "Exogamy, Latino/Black-Asian",
                "Exogamy, Latino/Black-Indigenous",
                "Exogamy, Latino/White-Asian",
                "Exogamy, Latino/White-Black",
                "Exogmay, Latino/White-Indigenous",
                "Exogamy, White/Asian",
                "Exogamy, White/Asian-Indigenous",
                "Exogamy, White/Black",
                "Exogamy, White/Black-Asian",
                "Exogamy, White/Black-Indigenous",
                "Exogamy, White/Indigenous",
                "Exogamy, White/Latino",
                "Exogamy, White/White-Asian",
                "Exogamy, White/White-Black",
                "Exogamy, White/White-Indigenous",
                "Exogamy, Asian-Indigenous M/Asian W",
                "Exogamy, Asian-Indigenous M/Black W",
                "Exogamy, Asian-Indigenous M/Indigenous W",
                "Exogamy, Asian-Indigenous M/Latino W",
                "Exogamy, Asian-Indigenous M/White W",
                "Exogamy, Asian M/Asian-Indigenous W",
                "Exogamy, Asian M/Black W",
                "Exogamy, Asian M/Black-Asian W",
                "Exogamy, Asian M/Black-Indigenous W",
                "Exogamy, Asian M/Indigenous W",
                "Exogamy, Asian M/Latino W",
                "Exogamy, Asian M/White W",
                "Exogamy, Asian M/White-Asian W",
                "Exogamy, Asian M/White-Black W",
                "Exogamy, Asian M/White-Indigenous W",
                "Exogamy, Black-Asian M/Asian W",
                "Exogamy, Black-Asian M/Black W",
                "Exogamy, Black-Asian M/Indigenous W",
                "Exogamy, Black-Asian M/Latino W",
                "Exogamy, Black-Asian M/White W",
                "Exogamy, Black-Indigenous M/Asian W",
                "Exogamy, Black-Indigenous M/Black W",
                "Exogamy, Black-Indigenous M/Indigenous W",
                "Exogamy, Black-Indigenous M/Latino W",
                "Exogamy, Black-Indigenous M/White W",
                "Exogamy, Black M/Asian W",
                "Exogamy, Black M/Asian-Indigenous W",
                "Exogamy, Black M/Black-Asian W",
                "Exogamy, Black M/Black-Indigenous W",
                "Exogamy, Black M/Indigenous W",
                "Exogamy, Black M/Latino W",
                "Exogamy, Black M/White W",
                "Exogamy, Black M/White-Asian W",
                "Exogamy, Black M/White-Black W",
                "Exogamy, Black M/White-Indigenous W",
                "Exogamy, Indigenous M/Asian W",
                "Exogamy, Indigenous M/Asian-Indigenous W",
                "Exogamy, Indigenous M/Black W",
                "Exogamy, Indigenous M/Black-Asian W",
                "Exogamy, Indigenous M/Black-Indigenous W",
                "Exogamy, Indigenous M/Latino W",
                "Exogamy, Indigenous M/White W",
                "Exogamy, Indigenous M/White-Asian W",
                "Exogamy, Indigenous M/White-Black W",
                "Exogamy, Indigenous M/White-Indigenous W",
                "Exogamy, Latino M/Asian W",
                "Exogamy, Latino M/Asian-Indigenous W",
                "Exogamy, Latino M/Black W",
                "Exogamy, Latino M/Black-Asian W",
                "Exogamy, Latino M/Black-Indigenous W",
                "Exogamy, Latino M/Indigenous W",
                "Exogamy, Latino M/White W",
                "Exogamy, Latino M/White-Asian W",
                "Exogamy, Latino M/White-Black W",
                "Exogamy, Latino M/White-Indigenous W",
                "Exogamy, multiracial/multiracial, no shared ancestry",
                "Exogamy, multiracial/multiracial, shared ancestry",
                "Exogamy, White-Asian M/Asian W",
                "Exogamy, White-Asian M/Black W",
                "Exogamy, White-Asian M/Indigenous W",
                "Exogamy, White-Asian M/Latino W",
                "Exogamy, White-Asian M/White W",
                "Exogamy, White-Black M/Asian W",
                "Exogamy, White-Black M/Black W",
                "Exogamy, White-Black M/Indigenous W",
                "Exogamy, White-Black M/Latino W",
                "Exogamy, White-Black M/White W",
                "Exogamy, White-Indigenous M/Asian W",
                "Exogamy, White-Indigenous M/Black W",
                "Exogamy, White-Indigenous M/Indigenous W",
                "Exogamy, White-Indigenous M/Latino W",
                "Exogamy, White-Indigenous M/White W",
                "Exogamy, White M/Asian W",
                "Exogamy, White M/Asian-Indigenous W",
                "Exogamy, White M/Black W",
                "Exogamy, White M/Black-Asian W",
                "Exogamy, White M/Black-Indigenous W",
                "Exogamy, White M/Indigenous W",
                "Exogamy, White M/Latino W",
                "Exogamy, White M/White-Asian W",
                "Exogamy, White M/White-Black W",
                "Exogamy, White M/White-Indigenous W")


texreg(lapply(list(model_full_sym_multi, model_short_sym_multi,
                   model_short_sym, model_short_asym), convertModel),
       digits=3,
       caption="Estimated og-odds ratios from conditional logit models predicting union formation",
       caption.above=TRUE,
       longtable = TRUE,
       use.packages = FALSE,
       custom.coef.names = coef_names,
       reorder.coef = c(1:14,32:36,15:31,37:76,77:156),
       groups = list("Control variables" = 1:9,
                     "Race of alternate partner" = 10:19,
                     "Multiracial-to-multiracial exogamy" = 20:36,
                     "Multi/monoracial-to-monoracial exogamy, symmetric" = 37:76,
                     "Multi/monoracial-to-monoracial exogamy, asymmetric" = 77:156))
```